eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
     payment-service:
              endpoint: http://PAYMENT-SERVICE/payment/save
spring:
      datasource:
             url: jdbc:mysql://localhost:3306/flipkart
             username: root
             password: admin
             driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
             ddl-auto: update
              
    
